registry:
    restart: always
    image: registry:2
    ports:
        - 5000:5000
    volumes:
        - ./data/registry:/var/lib/registry
        - ./configs/registry/certs:/certs

jenkins:
    build: docker/jenkins
    environment:
        - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
        - ./data/jenkins/home:/var/jenkins_home
    ports:
        - "8080:8080"

db:
    image: postgres
    volumes:
        - ./data/postgres:/var/lib/postgresql
    environment:
        - POSTGRESQL_USER=sonar
        - POSTGRESQL_PASS=sonar
        - POSTGRESQL_DB=sonar
    ports:
        - "5432:5432"
